$main =  "https://raw.githubusercontent.com/elizeusantosti/esti/main"
$powershell = "$home\documents\windowspowershell"
$modules = "$powershell\modules"
$pasta_scripts = "$powershell\scripts"
$dwservice = "https://www.dwservice.net/download/dwagent_x86.exe"