Set-Location $home\Desktop
write-Output . > teste.lnk
write-Output . > teste.exe
write-output . > teste.txt
write-output . > teste.doc
write-output . > teste.docx
write-output . > teste.xls
write-output . > teste.xlsx
write-output . > teste.pptx
write-output . > teste.pdf
write-output . > teste.html
write-output . > teste.css
write-output . > teste.js
write-output . > teste.py
write-output . > teste.jpg
write-output . > teste.png
write-output . > teste.mp3
write-output . > teste.wav
write-output . > teste.mp4
write-output . > teste.mov
write-output . > teste.mkv